package Lucky_Q;

import java.util.Random;

/**
 *  Kelas FrameQuiz ini berfungsi sebagai kelas utama dalam LuckyQuiz yang berisikan 
 *  Grapical User
 * 
 * @author LuckyQuizTeam
 * Projek PBO Angkatan 2017, 01-Januari-2019
 */
public class FrameQuiz extends javax.swing.JFrame {
    
    Dadu dadu = new Dadu();
    BankSoal bs = new BankSoal();
    Random ran = new Random();
    
    Pemain pem1 = new Pemain("Player1");
    Pemain pem2 = new Pemain("Player2");
    
    private int number;
    private int number2;
    
    /**
     * Creates new form FrameQuiz
     */
    public FrameQuiz() {
        initComponents();
        awal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Start = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rules = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        AboutUs = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Game = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Start.setOpaque(false);
        Start.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Start.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 650, 170, 70));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 44)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("START");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Start.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 190, 100));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("About Us");
        jButton3.setToolTipText("");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Start.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 170, 70));

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Rules");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Start.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 170, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky_Q/img/Start.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        Start.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 768));

        jLayeredPane1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        Profile.setOpaque(false);
        Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("NEXT");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Profile.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 650, 150, 60));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BACK");
        jButton5.setMaximumSize(new java.awt.Dimension(200, 60));
        jButton5.setMinimumSize(new java.awt.Dimension(200, 60));
        jButton5.setOpaque(false);
        jButton5.setPreferredSize(new java.awt.Dimension(200, 60));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Profile.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 150, 60));

        jTextField1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Profile.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 350, 55));

        jTextField2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        Profile.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 350, 55));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("!!! Player's Name Empty");
        Profile.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 210, 40));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("!!! Player's Name Empty");
        Profile.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 350, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky_Q/img/Profile.jpg"))); // NOI18N
        Profile.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        jLayeredPane1.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        Rules.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("BACK");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        Rules.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 150, 70));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky_Q/img/Rule.jpg"))); // NOI18N
        Rules.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        jLayeredPane1.add(Rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        AboutUs.setMaximumSize(new java.awt.Dimension(1366, 768));
        AboutUs.setMinimumSize(new java.awt.Dimension(1366, 768));
        AboutUs.setOpaque(false);
        AboutUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BACK");
        jButton6.setMaximumSize(new java.awt.Dimension(200, 60));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 60));
        jButton6.setPreferredSize(new java.awt.Dimension(200, 60));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        AboutUs.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 150, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky_Q/img/About.jpg"))); // NOI18N
        AboutUs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        jLayeredPane1.add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        Game.setMaximumSize(new java.awt.Dimension(1366, 768));
        Game.setMinimumSize(new java.awt.Dimension(1366, 768));
        Game.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        Game.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 20, 150, 150));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        Game.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 150, 150));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("NEXT");
        jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton13.setOpaque(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 110, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky_Q/img/Poor.jpg"))); // NOI18N
        jLabel24.setDisabledIcon(null);
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        Game.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 300, 600, 300));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField9.setToolTipText("");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 620, 130));

        jTextField10.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 510, 70));

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Question :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 150, 40));

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("SUBMIT");
        jButton12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 150, 40));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Answer :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, 40));

        Game.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 275, 620, 400));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("NEXT");
        jButton11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton11.setOpaque(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 110, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky_Q/img/Poor.jpg"))); // NOI18N
        jLabel5.setDisabledIcon(null);
        jLabel5.setMaximumSize(new java.awt.Dimension(600, 300));
        jLabel5.setMinimumSize(new java.awt.Dimension(600, 300));
        jLabel5.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        Game.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 600, 300));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField7.setToolTipText("");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 620, 130));

        jTextField8.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 510, 70));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Question :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 150, 40));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("SUBMIT");
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 150, 40));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Answer :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, 40));

        Game.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 275, 620, 400));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setMaximumSize(new java.awt.Dimension(300, 50));
        jTextField3.setMinimumSize(new java.awt.Dimension(300, 50));
        jTextField3.setName(""); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        Game.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, 60));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Game.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 150, 60));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        Game.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1016, 30, 300, 60));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        Game.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1166, 110, 150, 60));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("QUIT");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setMaximumSize(new java.awt.Dimension(200, 60));
        jButton7.setMinimumSize(new java.awt.Dimension(200, 60));
        jButton7.setPreferredSize(new java.awt.Dimension(200, 60));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Game.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 688, 200, 60));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SCORE");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Game.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 140, 60));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SCORE");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Game.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 60));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("ACAK");
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Game.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 150, 60));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("ACAK");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Game.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 190, 150, 60));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PLAYER 1 TURN");
        Game.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 700, 250, 50));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PLAYER 2 TURN");
        Game.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 700, 250, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky_Q/img/BiruMerah.jpg"))); // NOI18N
        Game.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Game.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 70, 30));

        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        Game.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 50, 70, 30));

        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        Game.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 50, 30));

        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setToolTipText("");
        Game.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 50, 30));

        jLayeredPane1.add(Game, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jTextField1.setText("");
        jTextField2.setText("");
        
        Profile.setVisible(true);
        Game.setVisible(false);
        Start.setVisible(false);
        AboutUs.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        Profile.setVisible(false);
        Game.setVisible(false);
        Start.setVisible(false);
        AboutUs.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!"".equals(jTextField1.getText()) && !"".equals(jTextField2.getText())){
            pem1.setNama(jTextField1.getText());
            pem2.setNama(jTextField2.getText());
            jTextField3.setText(pem1.getNama());
            jTextField4.setText("0");
            jTextField5.setText(pem2.getNama());
            jTextField6.setText("0");
            

            Profile.setVisible(false);
            Game.setVisible(true);
            Start.setVisible(false);
            AboutUs.setVisible(false);
            Rules.setVisible(false);
            jButton8.setVisible(true);
            jPanel5.setVisible(true);
            jButton9.setVisible(false);
            jPanel6.setVisible(true);
            jLabel18.setVisible(false);
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            
            
        }
        else if("".equals(jTextField1.getText()) && "".equals(jTextField2.getText())){
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
        }
        else if(!"".equals(jTextField1.getText()) && "".equals(jTextField2.getText())){
            jLabel9.setVisible(false);
            jLabel10.setVisible(true);
        }
        else if("".equals(jTextField1.getText()) && !"".equals(jTextField2.getText())){
            jLabel9.setVisible(true);
            jLabel10.setVisible(false);
        }
 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Profile.setVisible(false);
        Game.setVisible(false);
        Start.setVisible(true);
        AboutUs.setVisible(false);
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        
        jLabel8.setIcon(new javax.swing.ImageIcon("")); // NOI18N
        Game.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 60, 60));
        Game.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Profile.setVisible(false);
        Game.setVisible(false);
        Start.setVisible(true);
        AboutUs.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Profile.setVisible(false);
        Game.setVisible(false);
        Start.setVisible(true);
        AboutUs.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed

    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!jLabel12.getText().equals("P1")){
            jLabel12.setText("P1");
            jTextField8.setText("");
            setAcak1();
            setShowQuest1();    
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
            
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(!jLabel22.getText().equals("P2")){
            jLabel22.setText("P2");
            jTextField10.setText("");
            jLabel11.setVisible(true);
            setAcak2();
            setShowQuest2();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String ans = jTextField8.getText();
        int zz = Integer.parseInt(jLabel15.getText());
        jPanel2.setVisible(true);        
        jLabel5.setVisible(false);
        jLabel17.setVisible(true);

        if(ans.equalsIgnoreCase(bs.getJawab(zz))){
            pem1.setNilai(pem1.getNilai()+10);
            jTextField4.setText(String.valueOf(pem1.getNilai()));
            
            jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel17.setIcon(new javax.swing.ImageIcon("img\\Correct.jpg")); // NOI18N
            jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));
        }
        else{
            pem1.setNilai(pem1.getNilai()-10);
            jTextField4.setText(String.valueOf(pem1.getNilai()));
            

            jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel17.setIcon(new javax.swing.ImageIcon("img\\False.jpg")); // NOI18N
            jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));
        }
        jPanel1.setVisible(false);
        jButton8.setVisible(false);
        jLabel8.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jButton8.setVisible(false);
        jPanel5.setVisible(false);
        jLabel8.setVisible(false);
        jLabel18.setVisible(true);
        jPanel2.setVisible(false);
        jButton9.setVisible(true);
        jPanel6.setVisible(true);
        
        jLabel16.setVisible(false);
        jLabel12.setText("");
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String pp = jTextField10.getText();
        int xx = Integer.parseInt(jLabel23.getText());
        jPanel4.setVisible(true);
        jLabel24.setVisible(false);
        jLabel21.setVisible(true);
        if(pp.equalsIgnoreCase(bs.getJawab(xx))){
            pem2.setNilai(pem2.getNilai()+10);
            jTextField6.setText(String.valueOf(pem2.getNilai()));
            
            jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel21.setIcon(new javax.swing.ImageIcon("img/Correct.jpg")); // NOI18N
            jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));
        }
        else{
            pem2.setNilai(pem2.getNilai()-10);
            jTextField6.setText(String.valueOf(pem2.getNilai()));
            
            jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel21.setIcon(new javax.swing.ImageIcon("img/False.jpg")); // NOI18N
            jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));
        }

        jPanel3.setVisible(false);
        jButton9.setVisible(false);
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jButton9.setVisible(false);
        jPanel6.setVisible(false);
        jLabel11.setVisible(false);
        jPanel4.setVisible(false);
        jLabel18.setVisible(false);
        jButton8.setVisible(true);
        jPanel5.setVisible(true);
        jLabel16.setVisible(true);
        jLabel22.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Start.setVisible(false);
        Rules.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Rules.setVisible(false);
        Start.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    
    private void setAcak1(){
        number = dadu.getSisi();     
        jPanel5.setVisible(true);
        if(jLabel12.getText().equals("P1")){
            jLabel8.setVisible(true);
            switch(number){
                case 1 : {
                    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/1.jpg"))); // NOI18N
                    jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 2 : {
                    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/2.jpg"))); // NOI18N
                    jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 3 : {
                    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/3.jpg"))); // NOI18N
                    jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 4 : {
                    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/4.jpg"))); // NOI18N
                    jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 5 : {
                    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/5.jpg"))); // NOI18N
                    jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 6 : {
                    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/6.jpg"))); // NOI18N
                    jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
            }
        }
    }    
    
    private void setShowQuest1(){ 
        if((number==1 || number==3 || number==5)){
            jPanel1.setVisible(true);
            int any = ran.nextInt(50);
            String quest = bs.getSoal(any);
           
            jLabel15.setText(String.valueOf(any));
            jTextField7.setText(quest);
        }
        else if (number%2==0){
            jPanel2.setVisible(true);
            jLabel17.setVisible(false);
            jLabel5.setVisible(true);
            
        }
    }
   
    private void setAcak2(){
        number2 = dadu.getSisi();
        jPanel6.setVisible(true);
        if(jLabel22.getText().equals("P2")){
            jLabel11.setVisible(true);
            switch(number2){
                case 1 : {
                    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/1.jpg"))); // NOI18N
                    jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 2 : {
                    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/2.jpg"))); // NOI18N
                    jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 3 : {
                    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/3.jpg"))); // NOI18N
                    jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 4 : {
                    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/4.jpg"))); // NOI18N
                    jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 5 : {
                    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/5.jpg"))); // NOI18N
                    jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
                case 6 : {
                    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/6.jpg"))); // NOI18N
                    jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));
                    break;
                }
            }
        }
    }
    private void setShowQuest2(){  
        if((number2==2 || number2==4 || number2==6)){
            jPanel3.setVisible(true);
            int random = ran.nextInt(50);
            String quest1 = bs.getSoal(random);
           
            jLabel23.setText(String.valueOf(random));
            jTextField9.setText(quest1);
        }
        else{
            jPanel4.setVisible(true);
            jLabel21.setVisible(false);
            jLabel24.setVisible(true);
        }
    }  
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameQuiz().setVisible(true);
        });
    }
    
    private void awal(){
        Profile.setVisible(false);
        Game.setVisible(false);
        Start.setVisible(true);
        AboutUs.setVisible(false);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutUs;
    private javax.swing.JPanel Game;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel Rules;
    private javax.swing.JPanel Start;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
